[config]
language = "korean"

[pr_description]
publish_labels = true
add_original_user_description = true
generate_ai_title = true

[pr_reviewer]
require_score_review = false
require_tests_review = true
require_estimate_effort_to_review = true
num_code_suggestions = 20

[pr_code_suggestions]
num_code_suggestions = 20
