# 로컬 개발용 - MySQL만 컨테이너로 실행
# Spring Boot는 IntelliJ에서 직접 실행

services:
  mysql:
    image: mysql:8.0
    container_name: studyflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: studyflow
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis-server:
    image: redis:alpine
    container_name: studyflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379" # AOF를 켜고, 파일 크기가 이전보다 100% 커지거나 64mb를 넘으면 파일 크기를 줄이는(Rewrite) 최적화 명령 추가
    command: >
      redis-server  --requirepass ${REDIS_PASSWORD}  --appendonly yes  --auto-aof-rewrite-percentage 100  --auto-aof-rewrite-min-size 64mb
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
