spring:
  application:
    name: studyflow
  datasource:
    url: jdbc:mysql://localhost:3306/studyflow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: 
  access-token-expiration: 3600000      # 1시간
  refresh-token-expiration: 604800000   # 7일

cloud:
  aws:
    s3:
      bucket: studyflow-local
    region:
      static: ap-northeast-2
    credentials:
      access-key: your-access-key
      secret-key: your-secret-key

livekit:
  api-key: your-livekit-api-key
  api-secret: your-livekit-api-secret
  url: wss://your-livekit-url

server:
  port: 8080
